[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["pdfkit"]

[functions."generate-report"]
  included_files = ["node_modules/pdfkit/js/data/**"]
